version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie
    steps:
      - checkout
      - run: mkdir -p dist
      - run: cp index.html dist/
      - persist_to_workspace:
            root: dist
            paths:
              - '*'
  deploy-s3:
    docker:
      - image: cibuilds/aws
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy to S3
          command: aws s3 sync /tmp/workspace s3://lobor.rocks --delete --acl public-read
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-s3:
          requires:
            - build
          filters:
            branches:
              only: master